### PR TITLE
Find `pyproject.toml` in parent directories of `Cargo.toml`

### LINKED ISSUE #1053: Dependencies not added to the wheel metadata
### Bug Description

Dependencies specified in pyproject.toml are not added to the final METADA file in the dist-info directory.

I have [a project](https://github.com/cargo-lambda/cargo-lambda/blob/main/pyproject.toml#L5) with this information in the pyproject.toml file:

```
[project]
name = "cargo-lambda"
dependencies = ["ziglang>=0.9.0"]
```

When I read the documentation, I understood that Maturin would use that information to make sure that the dependencies are installed when someone runs `pip install cargo-lambda`. This is not the case.

For what I can tell, the `dist-info/METADATA` files doesn't include the dependency as `Requires-Dist`, is there anything that I'm missing?

This is the header if my `dist-info/METADATA`:

```
❯ cat cargo_lambda-0.10.0.dist-info/METADATA
Metadata-Version: 2.1
Name: cargo-lambda
Version: 0.10.0
Summary: Cargo subcommand to work with AWS Lambda
Keywords: cargo,subcommand,aws,lambda
Home-Page: https://github.com/cargo-lambda/cargo-lambda
License: MIT
Description-Content-Type: text/markdown; charset=UTF-8; variant=GFM
Project-URL: Source Code, https://github.com/cargo-lambda/cargo-lambda

# cargo-lambda

[![crates.io][crate-image]][crate-link]
[![Build Status][build-image]][build-link]
```

### Your Python version (`python -V`)

Python 3.8.10

### Your pip version (`pip -V`)

pip 20.0.2

### What bindings you're using

_No response_

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Clone cargo-lambda with `git clone git@github.com:cargo-lambda/cargo-lambda`
2. Generate a wheel with `maturin --release -o dist --strip -m crates/cargo-lambda-cli/Cargo.toml`
3. Unzip the generated wheel
4. Verify that `dist-info/METADATA` doesn't include `Requires-Dist`.

### PR DESCRIPTION
**Pull request by messense**
When `--manifest-path` is supplied via cli, lookup `pyproject.toml`
in its parent directories until workspace root.

Fixes #1053

### CODE REVIEW

File: src/project_layout.rs [hunk 1]
```diff
@@ -129,14 +129,24 @@ impl ProjectResolver {
...
     /// Get cargo manifest file path and pyproject.toml path
     fn resolve_manifest_paths(cargo_manifest_path: Option<PathBuf>) -> Result<(PathBuf, PathBuf)> {
+        let current_dir = env::current_dir()
+            .context("Failed to detect current directory ಠ_ಠ")?
+            .canonicalize()?;
         // use command line argument if specified
         if let Some(path) = cargo_manifest_path {
+            let manifest_file = path.canonicalize()?;
+            for parent in manifest_file.ancestors().skip(1) {
+                if !parent.starts_with(&current_dir) {
```
Comment (messense) [inline src/project_layout.rs:139]: FIXME: this should be workspace root instead of current working directory.
