### PR TITLE
Don't resolve python interpreter when building sdist only

### LINKED ISSUE #2245: Maturin sdist Generation Fails When Default Python Command Doesn't Exist
### Bug Description

Hello,

I have been working on getting Rust builds with maturin in our company's build system. This system isolates builds in an environment already and then runs `sys.executable -m build --sdist --outdir=<staging dir> --no-isolation`. Maturin then fails with ` Found pyo3 bindings
💥 maturin failed
  Caused by: Invalid python interpreter version`.

I traced this issue to https://github.com/PyO3/maturin/blob/main/src/build_options.rs#L1206. Here, maturin calls `python_ver.split_once('.')...`. However, in a no-isolation situation, for sdist generation, maturin gets the python interpreter from `target.get_python`. This will return `python3` for non-venv linux systems. When we try to `split_once` on that, it fails.

I'm happy to put up a fix for this if I can get some guidance on what the proper fix should be. We could first check for just a major version for example and go from there if that would work downstream.

Our build system is quite complicated, but I can reproduce this locally as well and with multiple python versions.

### Your maturin version (`maturin --version`)

1.7.4

### Your Python version (`python -V`)

3.12

### Your pip version (`pip -V`)

23.2.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Create a minimal python/rust library with just PyO3 as a dependency.
2. In a linux system, (no venv), install build and maturin.
3. Run `python3.12 -m build --sdist --no-isolation .`
4. Maturin should crash with the same error.

### PR DESCRIPTION
**Pull request by messense**
Alternative to #2283

Fixes #2245

### CODE REVIEW

**Comment by messense** [comment]
This change is part of the following stack:

- #2292 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

File: src/main.rs [hunk 1]
```diff
@@ -273,7 +273,13 @@ fn pep517(subcommand: Pep517Command) -> Result<()> {
             strip,
         } => {
             assert_eq!(build_options.interpreter.len(), 1);
-            let context = build_options.into_build_context(true, strip, false)?;
+            let context = build_options
+                .into_build_context()
+                .release(true)
+                .strip(strip)
+                .editable(false)
+                .sdist_only(true)
```
Comment (messense) [inline src/main.rs:281]:
```suggestion

```
