### PR TITLE
Fix auditwheel with read-only libraries

### LINKED ISSUE #1287: Permission denied error in add_external_libs when libary is not writable by owner
### Bug Description

The issue is that `patchelf` fails when invoked on the copy of the to-be-included library as the original permissions are retained and nothing guaranties that they are owner writable which is the case for all libraries on NixOS

Example:

```console
$ patchelf --set-soname libhs-19c0d7fc.so.5 /tmp/.tmpcBPM8J/libhs-19c0d7fc.so.5
patchelf: open: Permission denied
$ stat -c "Access: %a, UID: %u, GID: %g" /tmp/.tmpcBPM8J/libhs-19c0d7fc.so.5
Access: 555, UID: 1000, GID: 100
$ stat -c "Access: %a, UID: %u, GID: %g" /nix/store/l793dc6r9xagw7cfxv2w3bgwy9cy67yi-hyperscan-5.4.0/lib/libhs.so.5.4.0
Access: 555, UID: 0, GID: 0
```

I understand, there is an ongoing work to get rid of `patchelf`. In the meantime it could be mitigated by writing to a separate file via the `--output` flag of patchelf or fixing the permissions beforehand.

### Your Python version (`python -V`)

Python 3.8.15

### Your pip version (`pip -V`)

pip 22.2.2

### What bindings you're using

_No response_

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

I guess it is enough to set permissions to e..g `555` of a library dependency which gets picked up by auditwheel

### PR DESCRIPTION
**Pull request by vlaci**
`std::fs::copy` also copies the original file permissions. If the original library at `lib_path` was not writable, e.g. because it had its permission set to 0o555, the copy inherited the same permission causing later file manipulations, like `patchelf --set-soname` to fail.

Fixes #1287

### CODE REVIEW

File: src/build_context.rs [hunk 1]
```diff
@@ -392,6 +392,12 @@ impl BuildContext {
             fs::copy(&lib_path, &dest_path)?;
             libs_copied.insert(lib_path);
 
+            // fs::copy copies permissions as well, and the original
+            // file may have been read-only
+            let mut perms = fs::metadata(&dest_path)?.permissions();
+            perms.set_readonly(false);
+            fs::set_permissions(&dest_path, perms)?;
```
Comment (vlaci) [inline src/build_context.rs:399]: I thought about only setting the permission when needed, but didn't think that it worth the extra if condition to spare a few syscalls, as a stat is needed for each file anyway.

**Review by messense — APPROVED** [review]
Looks good to me, thanks!

bors r+

**Comment by messense** [comment]
Thanks for adding the changelog entry.

bors retry

**Comment by vlaci** [comment]
Thanks for the fast response.
